"""Idempotency-Key middleware (Task 2.2).

Standard pattern from the IETF idempotency-key draft:

  - Client picks a unique key per logical operation (UUIDv4 in practice)
    and sends it in the ``Idempotency-Key`` header on POST/PUT/PATCH/
    DELETE.
  - First request runs normally; the response (status + body + media
    type) is cached in Redis for 24h keyed by
    ``(token-hash, method, path, key)`` — scoping by token hash so two
    users using the same key independently don't collide.
  - A retry that arrives with the same key AND same body hash returns
    the cached response with a ``Idempotent-Replay: true`` header so
    callers can distinguish a replay from a fresh execution.
  - A retry with the same key but a DIFFERENT body hash returns 409
    ``idempotency_key_conflict`` — the client reused a key for a
    logically different request, which is a bug worth surfacing.

Add order in ``main.py``: CORS, Idempotency, CSRF. Starlette runs
middleware in reverse add order in the request path, so CSRF gates
incoming requests first; an attacker can't replay a cached response
without a valid CSRF token. Idempotency captures the response BEFORE
CSRF sets its csrf_token cookie, which is correct — replays carry
their own existing CSRF cookie from the original request, and the
fresh CSRF cookie is regenerated by the CSRF middleware on the way
out regardless of cache hit/miss.

We deliberately do NOT cache responses that include ``Set-Cookie``
(e.g. ``/api/auth/login`` issuing access_token). Replaying a cached
login body without the cookie would silently leave the client
un-authenticated, masking the failure as a success.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import re
from typing import Optional

from redis.asyncio import Redis
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse, Response

logger = logging.getLogger(__name__)

IDEMPOTENCY_HEADER = "Idempotency-Key"
REPLAY_HEADER = "Idempotent-Replay"
_TTL_SECONDS = 24 * 3600
_MUTATING = frozenset({"POST", "PUT", "PATCH", "DELETE"})
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9_\-]{8,128}$")

REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")

# Tests monkey-patch ``_test_client`` to a fakeredis instance so the
# middleware works without a real Redis. Production code never touches
# this attribute.
_test_client: Optional[Redis] = None


def _client() -> Redis:
    if _test_client is not None:
        return _test_client
    return Redis.from_url(REDIS_URL, decode_responses=False)


def _hash_token(token: str | None) -> str:
    """Identify the caller in the cache key without leaking the token.

    Anonymous requests share the ``anon`` slot, which is fine: an
    unauthenticated client retrying a registration with the same key +
    body should still get the cached response. We use a 16-char prefix
    of SHA-256 — collision probability over a 24h window is negligible
    and it keeps Redis keys short.
    """
    if not token:
        return "anon"
    return hashlib.sha256(token.encode()).hexdigest()[:16]


def _hash_body(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def _cache_key(token_hash: str, method: str, path: str, query: str, key: str) -> str:
    suffix = f"?{query}" if query else ""
    return f"idem:{token_hash}:{method}:{path}{suffix}:{key}"


def _conflict_response() -> JSONResponse:
    return JSONResponse(
        status_code=409,
        content={
            "detail": "Idempotency-Key reused with a different request body",
            "code": "idempotency_key_conflict",
        },
    )


def _bad_key_response() -> JSONResponse:
    return JSONResponse(
        status_code=400,
        content={
            "detail": "Invalid Idempotency-Key format",
            "code": "invalid_idempotency_key",
        },
    )


class IdempotencyMiddleware(BaseHTTPMiddleware):
    """Cache successful mutating responses keyed by ``Idempotency-Key``."""

    async def dispatch(self, request: Request, call_next) -> Response:
        if request.method not in _MUTATING:
            return await call_next(request)

        key = request.headers.get(IDEMPOTENCY_HEADER)
        if not key:
            return await call_next(request)

        if not _KEY_PATTERN.match(key):
            return _bad_key_response()

        # Drain the body so we can hash it AND replay it to the
        # downstream app. Starlette consumes the receive stream on
        # ``await request.body()``, so we monkey-patch ``_receive``
        # with a closure that hands the cached body back to the app.
        body = await request.body()
        body_hash = _hash_body(body)

        async def _receive():
            return {"type": "http.request", "body": body, "more_body": False}

        request._receive = _receive  # type: ignore[attr-defined]

        token_hash = _hash_token(request.cookies.get("access_token"))
        cache_key = _cache_key(
            token_hash,
            request.method,
            request.url.path,
            request.url.query,
            key,
        )

        client = _client()
        cached_raw = None
        try:
            cached_raw = await client.get(cache_key)
        except Exception as exc:  # noqa: BLE001 — Redis hiccup shouldn't break the request
            logger.warning("idempotency cache read failed: %s", exc)

        if cached_raw:
            try:
                cached = json.loads(cached_raw)
            except (json.JSONDecodeError, TypeError):
                logger.warning("idempotency cache value corrupt for %s", cache_key)
                cached = None

            if cached:
                if cached.get("body_hash") != body_hash:
                    return _conflict_response()
                return Response(
                    content=cached["body"].encode("utf-8"),
                    status_code=cached["status_code"],
                    media_type=cached.get("media_type") or "application/json",
                    headers={REPLAY_HEADER: "true"},
                )

        response = await call_next(request)

        # Only 2xx responses are cacheable. Errors should re-run on
        # retry — the client may have fixed the root cause.
        if not (200 <= response.status_code < 300):
            return response

        # Refuse to cache anything that sets cookies. The most obvious
        # offender is ``/api/auth/login`` issuing ``access_token`` — a
        # cached replay without the cookie would silently keep the
        # client logged out.
        if "set-cookie" in (h.lower() for h in response.headers.keys()):
            return response

        body_chunks: list[bytes] = []
        async for chunk in response.body_iterator:
            body_chunks.append(chunk)
        response_body = b"".join(body_chunks)

        payload = json.dumps(
            {
                "body_hash": body_hash,
                "status_code": response.status_code,
                "body": response_body.decode("utf-8", errors="replace"),
                "media_type": response.media_type or "application/json",
            }
        )
        try:
            await client.set(cache_key, payload, ex=_TTL_SECONDS)
        except Exception as exc:  # noqa: BLE001
            logger.warning("idempotency cache write failed: %s", exc)

        # Rebuild the response with the captured body. ``content-length``
        # is rebuilt by ``Response.__init__`` so we drop the original.
        rebuilt_headers = dict(response.headers)
        rebuilt_headers.pop("content-length", None)
        return Response(
            content=response_body,
            status_code=response.status_code,
            media_type=response.media_type or "application/json",
            headers=rebuilt_headers,
        )
